#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 132
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 8

enum {
  anon_sym_end = 1,
  sym_return_statement = 2,
  anon_sym_local = 3,
  anon_sym_EQ = 4,
  anon_sym_function = 5,
  anon_sym_LPAREN_RPAREN = 6,
  anon_sym_DOT = 7,
  anon_sym_COLON = 8,
  anon_sym_COMMA = 9,
  anon_sym_or = 10,
  anon_sym_and = 11,
  anon_sym_LT = 12,
  anon_sym_LT_EQ = 13,
  anon_sym_EQ_EQ = 14,
  anon_sym_TILDE_EQ = 15,
  anon_sym_GT_EQ = 16,
  anon_sym_GT = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_STAR = 20,
  anon_sym_SLASH = 21,
  anon_sym_DOT_DOT = 22,
  anon_sym_CARET = 23,
  anon_sym_LBRACK = 24,
  anon_sym_RBRACK = 25,
  sym_identifier = 26,
  sym_number = 27,
  sym_chunk = 28,
  sym_terminated_chunk = 29,
  sym__statement = 30,
  sym_local_assign_statement = 31,
  sym_assign_statement = 32,
  sym_function_declaration_statement = 33,
  sym__function_name = 34,
  sym_function_name_dot_index = 35,
  sym_function_name_self_index = 36,
  sym_expression_list = 37,
  sym__expression = 38,
  sym_binary_expression = 39,
  sym_variable_list = 40,
  sym__variable = 41,
  sym_variable_dot_index = 42,
  sym_variable_sub_index = 43,
  sym_identifier_list = 44,
  aux_sym_chunk_repeat1 = 45,
  aux_sym_expression_list_repeat1 = 46,
  aux_sym_variable_list_repeat1 = 47,
  aux_sym_identifier_list_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_end] = "end",
  [sym_return_statement] = "return_statement",
  [anon_sym_local] = "local",
  [anon_sym_EQ] = "=",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN_RPAREN] = "()",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_TILDE_EQ] = "~=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_CARET] = "^",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_chunk] = "chunk",
  [sym_terminated_chunk] = "terminated_chunk",
  [sym__statement] = "_statement",
  [sym_local_assign_statement] = "local_assign_statement",
  [sym_assign_statement] = "assign_statement",
  [sym_function_declaration_statement] = "function_declaration_statement",
  [sym__function_name] = "_function_name",
  [sym_function_name_dot_index] = "function_name_dot_index",
  [sym_function_name_self_index] = "function_name_self_index",
  [sym_expression_list] = "expression_list",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_variable_list] = "variable_list",
  [sym__variable] = "_variable",
  [sym_variable_dot_index] = "variable_dot_index",
  [sym_variable_sub_index] = "variable_sub_index",
  [sym_identifier_list] = "identifier_list",
  [aux_sym_chunk_repeat1] = "chunk_repeat1",
  [aux_sym_expression_list_repeat1] = "expression_list_repeat1",
  [aux_sym_variable_list_repeat1] = "variable_list_repeat1",
  [aux_sym_identifier_list_repeat1] = "identifier_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_end] = anon_sym_end,
  [sym_return_statement] = sym_return_statement,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN_RPAREN] = anon_sym_LPAREN_RPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_TILDE_EQ] = anon_sym_TILDE_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_chunk] = sym_chunk,
  [sym_terminated_chunk] = sym_terminated_chunk,
  [sym__statement] = sym__statement,
  [sym_local_assign_statement] = sym_local_assign_statement,
  [sym_assign_statement] = sym_assign_statement,
  [sym_function_declaration_statement] = sym_function_declaration_statement,
  [sym__function_name] = sym__function_name,
  [sym_function_name_dot_index] = sym_function_name_dot_index,
  [sym_function_name_self_index] = sym_function_name_self_index,
  [sym_expression_list] = sym_expression_list,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_variable_list] = sym_variable_list,
  [sym__variable] = sym__variable,
  [sym_variable_dot_index] = sym_variable_dot_index,
  [sym_variable_sub_index] = sym_variable_sub_index,
  [sym_identifier_list] = sym_identifier_list,
  [aux_sym_chunk_repeat1] = aux_sym_chunk_repeat1,
  [aux_sym_expression_list_repeat1] = aux_sym_expression_list_repeat1,
  [aux_sym_variable_list_repeat1] = aux_sym_variable_list_repeat1,
  [aux_sym_identifier_list_repeat1] = aux_sym_identifier_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_terminated_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_local_assign_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__function_name] = {
    .visible = false,
    .named = true,
  },
  [sym_function_name_dot_index] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name_self_index] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_list] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_list] = {
    .visible = true,
    .named = true,
  },
  [sym__variable] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_dot_index] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_sub_index] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_chunk_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_expression = 2,
  field_expressions = 3,
  field_identifier = 4,
  field_identifiers = 5,
  field_name = 6,
  field_variable = 7,
  field_variables = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_expression] = "expression",
  [field_expressions] = "expressions",
  [field_identifier] = "identifier",
  [field_identifiers] = "identifiers",
  [field_name] = "name",
  [field_variable] = "variable",
  [field_variables] = "variables",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_identifiers, 1},
  [1] =
    {field_expressions, 2},
    {field_variables, 0},
  [3] =
    {field_identifier, 2},
    {field_variable, 0},
  [5] =
    {field_expressions, 3},
    {field_identifiers, 1},
  [7] =
    {field_body, 3},
    {field_name, 1},
  [9] =
    {field_expression, 2},
    {field_variable, 0},
  [11] =
    {field_identifier, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '(') ADVANCE(1);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '+') ADVANCE(45);
      if (lookahead == ',') ADVANCE(34);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead == '0') ADVANCE(75);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '[') ADVANCE(51);
      if (lookahead == ']') ADVANCE(52);
      if (lookahead == '^') ADVANCE(50);
      if (lookahead == 'a') ADVANCE(61);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == 'o') ADVANCE(68);
      if (lookahead == 'r') ADVANCE(58);
      if (lookahead == '~') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '+') ADVANCE(45);
      if (lookahead == ',') ADVANCE(34);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '[') ADVANCE(51);
      if (lookahead == '^') ADVANCE(50);
      if (lookahead == 'a') ADVANCE(61);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == 'o') ADVANCE(68);
      if (lookahead == 'r') ADVANCE(58);
      if (lookahead == '~') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '+') ADVANCE(45);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '[') ADVANCE(51);
      if (lookahead == ']') ADVANCE(52);
      if (lookahead == '^') ADVANCE(50);
      if (lookahead == 'a') ADVANCE(10);
      if (lookahead == 'e') ADVANCE(11);
      if (lookahead == 'o') ADVANCE(12);
      if (lookahead == '~') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == ',') ADVANCE(34);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == 'r') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '0') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(77);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      END_STATE();
    case 18:
      if (eof) ADVANCE(21);
      if (lookahead == '(') ADVANCE(1);
      if (lookahead == ',') ADVANCE(34);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '[') ADVANCE(51);
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == 'r') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(18)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 19:
      if (eof) ADVANCE(21);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '+') ADVANCE(45);
      if (lookahead == ',') ADVANCE(34);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '[') ADVANCE(51);
      if (lookahead == '^') ADVANCE(50);
      if (lookahead == 'a') ADVANCE(61);
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == 'o') ADVANCE(68);
      if (lookahead == 'r') ADVANCE(58);
      if (lookahead == '~') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(19)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '+') ADVANCE(45);
      if (lookahead == ',') ADVANCE(34);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '[') ADVANCE(51);
      if (lookahead == '^') ADVANCE(50);
      if (lookahead == 'a') ADVANCE(61);
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == 'o') ADVANCE(68);
      if (lookahead == 'r') ADVANCE(58);
      if (lookahead == '~') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(20)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_end);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_return_statement);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_local);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_function);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LPAREN_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(49);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_or);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_and);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_TILDE_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(53);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(78);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(16);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(78);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 19},
  [3] = {.lex_state = 19},
  [4] = {.lex_state = 20},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 20},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 20},
  [17] = {.lex_state = 20},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 20},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 20},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 20},
  [24] = {.lex_state = 20},
  [25] = {.lex_state = 20},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 18},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 18},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 18},
  [50] = {.lex_state = 18},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 18},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 18},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 18},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 5},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 5},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 5},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 18},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 4},
  [89] = {.lex_state = 18},
  [90] = {.lex_state = 18},
  [91] = {.lex_state = 4},
  [92] = {.lex_state = 18},
  [93] = {.lex_state = 18},
  [94] = {.lex_state = 18},
  [95] = {.lex_state = 18},
  [96] = {.lex_state = 4},
  [97] = {.lex_state = 4},
  [98] = {.lex_state = 18},
  [99] = {.lex_state = 4},
  [100] = {.lex_state = 4},
  [101] = {.lex_state = 18},
  [102] = {.lex_state = 4},
  [103] = {.lex_state = 18},
  [104] = {.lex_state = 5},
  [105] = {.lex_state = 18},
  [106] = {.lex_state = 5},
  [107] = {.lex_state = 5},
  [108] = {.lex_state = 18},
  [109] = {.lex_state = 18},
  [110] = {.lex_state = 18},
  [111] = {.lex_state = 5},
  [112] = {.lex_state = 5},
  [113] = {.lex_state = 18},
  [114] = {.lex_state = 18},
  [115] = {.lex_state = 18},
  [116] = {.lex_state = 5},
  [117] = {.lex_state = 5},
  [118] = {.lex_state = 18},
  [119] = {.lex_state = 5},
  [120] = {.lex_state = 5},
  [121] = {.lex_state = 18},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 3},
  [124] = {.lex_state = 3},
  [125] = {.lex_state = 3},
  [126] = {.lex_state = 5},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 5},
  [130] = {.lex_state = 3},
  [131] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [sym_return_statement] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_TILDE_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_chunk] = STATE(122),
    [sym__statement] = STATE(44),
    [sym_local_assign_statement] = STATE(44),
    [sym_assign_statement] = STATE(44),
    [sym_function_declaration_statement] = STATE(44),
    [sym_variable_list] = STATE(121),
    [sym__variable] = STATE(92),
    [sym_variable_dot_index] = STATE(92),
    [sym_variable_sub_index] = STATE(92),
    [aux_sym_chunk_repeat1] = STATE(44),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_return_statement] = ACTIONS(5),
    [anon_sym_local] = ACTIONS(7),
    [anon_sym_function] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(15), 10,
      sym_return_statement,
      anon_sym_local,
      anon_sym_EQ,
      anon_sym_function,
      anon_sym_DOT,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(13), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_CARET,
      anon_sym_LBRACK,
  [28] = 2,
    ACTIONS(19), 10,
      sym_return_statement,
      anon_sym_local,
      anon_sym_EQ,
      anon_sym_function,
      anon_sym_DOT,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(17), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_CARET,
      anon_sym_LBRACK,
  [56] = 4,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 8,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(21), 12,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_CARET,
  [87] = 4,
    ACTIONS(29), 1,
      anon_sym_DOT,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 9,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(21), 11,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_CARET,
  [118] = 2,
    ACTIONS(19), 10,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_DOT,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(17), 12,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_CARET,
      anon_sym_LBRACK,
  [145] = 2,
    ACTIONS(15), 10,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_DOT,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(13), 12,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_CARET,
      anon_sym_LBRACK,
  [172] = 12,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      anon_sym_COMMA,
    ACTIONS(39), 1,
      anon_sym_or,
    ACTIONS(41), 1,
      anon_sym_and,
    ACTIONS(51), 1,
      anon_sym_DOT_DOT,
    ACTIONS(53), 1,
      anon_sym_CARET,
    STATE(81), 1,
      aux_sym_expression_list_repeat1,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(49), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(35), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
    ACTIONS(45), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
  [218] = 11,
    ACTIONS(55), 1,
      anon_sym_COMMA,
    ACTIONS(57), 1,
      anon_sym_or,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(69), 1,
      anon_sym_DOT_DOT,
    ACTIONS(71), 1,
      anon_sym_CARET,
    STATE(87), 1,
      aux_sym_expression_list_repeat1,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(63), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(35), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [262] = 3,
    ACTIONS(71), 1,
      anon_sym_CARET,
    ACTIONS(73), 9,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(75), 10,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
  [289] = 3,
    ACTIONS(71), 1,
      anon_sym_CARET,
    ACTIONS(73), 9,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(75), 10,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
  [316] = 4,
    ACTIONS(71), 1,
      anon_sym_CARET,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 8,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DOT_DOT,
    ACTIONS(73), 9,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
  [345] = 6,
    ACTIONS(69), 1,
      anon_sym_DOT_DOT,
    ACTIONS(71), 1,
      anon_sym_CARET,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 5,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(73), 9,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
  [378] = 8,
    ACTIONS(69), 1,
      anon_sym_DOT_DOT,
    ACTIONS(71), 1,
      anon_sym_CARET,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(63), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(73), 7,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [415] = 9,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(69), 1,
      anon_sym_DOT_DOT,
    ACTIONS(71), 1,
      anon_sym_CARET,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(63), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(73), 6,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      sym_identifier,
  [454] = 8,
    ACTIONS(51), 1,
      anon_sym_DOT_DOT,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(49), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(45), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(73), 6,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      sym_identifier,
  [491] = 3,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(73), 8,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(75), 11,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
  [518] = 4,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(49), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(73), 8,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(75), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DOT_DOT,
  [547] = 6,
    ACTIONS(51), 1,
      anon_sym_DOT_DOT,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(49), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(73), 8,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
  [580] = 6,
    ACTIONS(69), 1,
      anon_sym_DOT_DOT,
    ACTIONS(71), 1,
      anon_sym_CARET,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 5,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(73), 9,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
  [613] = 6,
    ACTIONS(51), 1,
      anon_sym_DOT_DOT,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(49), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(73), 8,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
  [646] = 10,
    ACTIONS(57), 1,
      anon_sym_or,
    ACTIONS(59), 1,
      anon_sym_and,
    ACTIONS(69), 1,
      anon_sym_DOT_DOT,
    ACTIONS(71), 1,
      anon_sym_CARET,
    ACTIONS(79), 1,
      anon_sym_COMMA,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(67), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(63), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(77), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [687] = 3,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(73), 8,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(75), 11,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
  [714] = 10,
    ACTIONS(39), 1,
      anon_sym_or,
    ACTIONS(41), 1,
      anon_sym_and,
    ACTIONS(51), 1,
      anon_sym_DOT_DOT,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(49), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(45), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(77), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [755] = 9,
    ACTIONS(41), 1,
      anon_sym_and,
    ACTIONS(51), 1,
      anon_sym_DOT_DOT,
    ACTIONS(53), 1,
      anon_sym_CARET,
    ACTIONS(43), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(49), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(45), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
    ACTIONS(73), 5,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      anon_sym_or,
      sym_identifier,
  [794] = 4,
    ACTIONS(81), 1,
      anon_sym_DOT,
    ACTIONS(83), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 13,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_CARET,
      anon_sym_RBRACK,
  [820] = 2,
    ACTIONS(15), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(13), 14,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_CARET,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [842] = 2,
    ACTIONS(19), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(17), 14,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_CARET,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [864] = 9,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(85), 1,
      anon_sym_end,
    ACTIONS(87), 1,
      sym_return_statement,
    ACTIONS(89), 1,
      anon_sym_local,
    ACTIONS(91), 1,
      anon_sym_function,
    STATE(101), 1,
      sym_terminated_chunk,
    STATE(118), 1,
      sym_variable_list,
    STATE(92), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
    STATE(45), 5,
      sym__statement,
      sym_local_assign_statement,
      sym_assign_statement,
      sym_function_declaration_statement,
      aux_sym_chunk_repeat1,
  [898] = 9,
    ACTIONS(93), 1,
      anon_sym_or,
    ACTIONS(95), 1,
      anon_sym_and,
    ACTIONS(105), 1,
      anon_sym_DOT_DOT,
    ACTIONS(107), 1,
      anon_sym_CARET,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
    ACTIONS(97), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(99), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
  [932] = 4,
    ACTIONS(107), 1,
      anon_sym_CARET,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 10,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DOT_DOT,
      anon_sym_RBRACK,
  [956] = 3,
    ACTIONS(107), 1,
      anon_sym_CARET,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 12,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_RBRACK,
  [978] = 6,
    ACTIONS(105), 1,
      anon_sym_DOT_DOT,
    ACTIONS(107), 1,
      anon_sym_CARET,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 7,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1006] = 7,
    ACTIONS(105), 1,
      anon_sym_DOT_DOT,
    ACTIONS(107), 1,
      anon_sym_CARET,
    ACTIONS(97), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 3,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RBRACK,
    ACTIONS(99), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
  [1036] = 8,
    ACTIONS(95), 1,
      anon_sym_and,
    ACTIONS(105), 1,
      anon_sym_DOT_DOT,
    ACTIONS(107), 1,
      anon_sym_CARET,
    ACTIONS(75), 2,
      anon_sym_or,
      anon_sym_RBRACK,
    ACTIONS(97), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(99), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
  [1068] = 9,
    ACTIONS(93), 1,
      anon_sym_or,
    ACTIONS(95), 1,
      anon_sym_and,
    ACTIONS(105), 1,
      anon_sym_DOT_DOT,
    ACTIONS(107), 1,
      anon_sym_CARET,
    ACTIONS(111), 1,
      anon_sym_RBRACK,
    ACTIONS(97), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(99), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
  [1102] = 9,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_local,
    ACTIONS(91), 1,
      anon_sym_function,
    ACTIONS(113), 1,
      anon_sym_end,
    ACTIONS(115), 1,
      sym_return_statement,
    STATE(91), 1,
      sym_terminated_chunk,
    STATE(118), 1,
      sym_variable_list,
    STATE(92), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
    STATE(42), 5,
      sym__statement,
      sym_local_assign_statement,
      sym_assign_statement,
      sym_function_declaration_statement,
      aux_sym_chunk_repeat1,
  [1136] = 6,
    ACTIONS(105), 1,
      anon_sym_DOT_DOT,
    ACTIONS(107), 1,
      anon_sym_CARET,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 7,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1164] = 3,
    ACTIONS(107), 1,
      anon_sym_CARET,
    ACTIONS(73), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 12,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT_DOT,
      anon_sym_RBRACK,
  [1186] = 9,
    ACTIONS(93), 1,
      anon_sym_or,
    ACTIONS(95), 1,
      anon_sym_and,
    ACTIONS(105), 1,
      anon_sym_DOT_DOT,
    ACTIONS(107), 1,
      anon_sym_CARET,
    ACTIONS(117), 1,
      anon_sym_RBRACK,
    ACTIONS(97), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(99), 4,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_TILDE_EQ,
      anon_sym_GT_EQ,
  [1220] = 8,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 1,
      sym_return_statement,
    ACTIONS(123), 1,
      anon_sym_local,
    ACTIONS(126), 1,
      anon_sym_function,
    ACTIONS(129), 1,
      sym_identifier,
    STATE(121), 1,
      sym_variable_list,
    STATE(92), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
    STATE(41), 5,
      sym__statement,
      sym_local_assign_statement,
      sym_assign_statement,
      sym_function_declaration_statement,
      aux_sym_chunk_repeat1,
  [1251] = 8,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_local,
    ACTIONS(91), 1,
      anon_sym_function,
    ACTIONS(132), 1,
      anon_sym_end,
    ACTIONS(134), 1,
      sym_return_statement,
    STATE(118), 1,
      sym_variable_list,
    STATE(92), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
    STATE(43), 5,
      sym__statement,
      sym_local_assign_statement,
      sym_assign_statement,
      sym_function_declaration_statement,
      aux_sym_chunk_repeat1,
  [1282] = 7,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_local,
    ACTIONS(139), 1,
      anon_sym_function,
    STATE(118), 1,
      sym_variable_list,
    ACTIONS(121), 2,
      anon_sym_end,
      sym_return_statement,
    STATE(92), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
    STATE(43), 5,
      sym__statement,
      sym_local_assign_statement,
      sym_assign_statement,
      sym_function_declaration_statement,
      aux_sym_chunk_repeat1,
  [1311] = 8,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 1,
      sym_return_statement,
    STATE(121), 1,
      sym_variable_list,
    STATE(92), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
    STATE(41), 5,
      sym__statement,
      sym_local_assign_statement,
      sym_assign_statement,
      sym_function_declaration_statement,
      aux_sym_chunk_repeat1,
  [1342] = 8,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_local,
    ACTIONS(91), 1,
      anon_sym_function,
    ACTIONS(146), 1,
      anon_sym_end,
    ACTIONS(148), 1,
      sym_return_statement,
    STATE(118), 1,
      sym_variable_list,
    STATE(92), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
    STATE(43), 5,
      sym__statement,
      sym_local_assign_statement,
      sym_assign_statement,
      sym_function_declaration_statement,
      aux_sym_chunk_repeat1,
  [1373] = 5,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(152), 1,
      sym_number,
    STATE(97), 1,
      sym_expression_list,
    STATE(9), 2,
      sym__expression,
      sym_binary_expression,
    STATE(5), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1392] = 4,
    ACTIONS(156), 1,
      anon_sym_EQ,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(154), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1409] = 5,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(152), 1,
      sym_number,
    STATE(96), 1,
      sym_expression_list,
    STATE(9), 2,
      sym__expression,
      sym_binary_expression,
    STATE(5), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1428] = 4,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      anon_sym_EQ,
    ACTIONS(154), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1445] = 4,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      anon_sym_EQ,
    ACTIONS(164), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1462] = 5,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(171), 1,
      sym_number,
    STATE(98), 1,
      sym_expression_list,
    STATE(8), 2,
      sym__expression,
      sym_binary_expression,
    STATE(4), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1481] = 4,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_EQ,
    ACTIONS(175), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1498] = 4,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(173), 1,
      anon_sym_EQ,
    STATE(47), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(175), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1515] = 4,
    ACTIONS(162), 1,
      anon_sym_EQ,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_identifier_list_repeat1,
    ACTIONS(164), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1532] = 5,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(171), 1,
      sym_number,
    STATE(90), 1,
      sym_expression_list,
    STATE(8), 2,
      sym__expression,
      sym_binary_expression,
    STATE(4), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1551] = 3,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_expression_list_repeat1,
    ACTIONS(77), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1565] = 4,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(185), 1,
      sym_number,
    STATE(34), 2,
      sym__expression,
      sym_binary_expression,
    STATE(26), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1581] = 4,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(187), 1,
      sym_number,
    STATE(30), 2,
      sym__expression,
      sym_binary_expression,
    STATE(26), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1597] = 4,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(189), 1,
      sym_number,
    STATE(36), 2,
      sym__expression,
      sym_binary_expression,
    STATE(26), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1613] = 2,
    ACTIONS(162), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(164), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1625] = 4,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(191), 1,
      sym_number,
    STATE(40), 2,
      sym__expression,
      sym_binary_expression,
    STATE(26), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1641] = 4,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_expression_list_repeat1,
    ACTIONS(77), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1657] = 4,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(196), 1,
      sym_number,
    STATE(10), 2,
      sym__expression,
      sym_binary_expression,
    STATE(5), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1673] = 4,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(198), 1,
      sym_number,
    STATE(20), 2,
      sym__expression,
      sym_binary_expression,
    STATE(5), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1689] = 4,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(200), 1,
      sym_number,
    STATE(24), 2,
      sym__expression,
      sym_binary_expression,
    STATE(4), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1705] = 4,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(202), 1,
      sym_number,
    STATE(11), 2,
      sym__expression,
      sym_binary_expression,
    STATE(5), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1721] = 4,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(204), 1,
      sym_number,
    STATE(23), 2,
      sym__expression,
      sym_binary_expression,
    STATE(4), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1737] = 4,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(206), 1,
      sym_number,
    STATE(19), 2,
      sym__expression,
      sym_binary_expression,
    STATE(4), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1753] = 4,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(208), 1,
      sym_number,
    STATE(17), 2,
      sym__expression,
      sym_binary_expression,
    STATE(4), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1769] = 4,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(210), 1,
      sym_number,
    STATE(12), 2,
      sym__expression,
      sym_binary_expression,
    STATE(5), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1785] = 4,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(212), 1,
      sym_number,
    STATE(18), 2,
      sym__expression,
      sym_binary_expression,
    STATE(4), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1801] = 4,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(214), 1,
      sym_number,
    STATE(21), 2,
      sym__expression,
      sym_binary_expression,
    STATE(4), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1817] = 4,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(216), 1,
      sym_number,
    STATE(16), 2,
      sym__expression,
      sym_binary_expression,
    STATE(4), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1833] = 2,
    ACTIONS(162), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(164), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1845] = 4,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(218), 1,
      sym_number,
    STATE(25), 2,
      sym__expression,
      sym_binary_expression,
    STATE(4), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1861] = 4,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(220), 1,
      sym_number,
    STATE(13), 2,
      sym__expression,
      sym_binary_expression,
    STATE(5), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1877] = 4,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(222), 1,
      sym_number,
    STATE(14), 2,
      sym__expression,
      sym_binary_expression,
    STATE(5), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1893] = 4,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(224), 1,
      sym_number,
    STATE(15), 2,
      sym__expression,
      sym_binary_expression,
    STATE(5), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1909] = 4,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(226), 1,
      sym_number,
    STATE(22), 2,
      sym__expression,
      sym_binary_expression,
    STATE(5), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1925] = 4,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(228), 1,
      sym_number,
    STATE(35), 2,
      sym__expression,
      sym_binary_expression,
    STATE(26), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1941] = 4,
    ACTIONS(37), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
    STATE(62), 1,
      aux_sym_expression_list_repeat1,
    ACTIONS(232), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [1957] = 4,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(234), 1,
      sym_number,
    STATE(33), 2,
      sym__expression,
      sym_binary_expression,
    STATE(26), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1973] = 4,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(236), 1,
      sym_number,
    STATE(31), 2,
      sym__expression,
      sym_binary_expression,
    STATE(26), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [1989] = 4,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(238), 1,
      sym_number,
    STATE(39), 2,
      sym__expression,
      sym_binary_expression,
    STATE(26), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [2005] = 4,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(240), 1,
      sym_number,
    STATE(38), 2,
      sym__expression,
      sym_binary_expression,
    STATE(26), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [2021] = 4,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(242), 1,
      sym_number,
    STATE(32), 2,
      sym__expression,
      sym_binary_expression,
    STATE(26), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [2037] = 3,
    ACTIONS(55), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_expression_list_repeat1,
    ACTIONS(232), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2051] = 2,
    ACTIONS(246), 1,
      anon_sym_EQ,
    ACTIONS(244), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2062] = 3,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
    ACTIONS(250), 1,
      anon_sym_EQ,
    ACTIONS(244), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2075] = 2,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
    ACTIONS(254), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2085] = 1,
    ACTIONS(256), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2093] = 5,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(258), 1,
      anon_sym_EQ,
    ACTIONS(260), 1,
      anon_sym_DOT,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    STATE(108), 1,
      aux_sym_variable_list_repeat1,
  [2109] = 2,
    ACTIONS(264), 1,
      ts_builtin_sym_end,
    ACTIONS(266), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2119] = 2,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
    ACTIONS(270), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2129] = 2,
    ACTIONS(272), 1,
      ts_builtin_sym_end,
    ACTIONS(274), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2139] = 1,
    ACTIONS(276), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2147] = 1,
    ACTIONS(254), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2155] = 2,
    ACTIONS(278), 1,
      ts_builtin_sym_end,
    ACTIONS(276), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2165] = 1,
    ACTIONS(274), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2173] = 1,
    ACTIONS(266), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2181] = 2,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
    ACTIONS(256), 4,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2191] = 1,
    ACTIONS(270), 5,
      anon_sym_end,
      sym_return_statement,
      anon_sym_local,
      anon_sym_function,
      sym_identifier,
  [2199] = 3,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(260), 1,
      anon_sym_DOT,
    ACTIONS(282), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [2210] = 2,
    ACTIONS(284), 1,
      sym_identifier,
    STATE(103), 3,
      sym__variable,
      sym_variable_dot_index,
      sym_variable_sub_index,
  [2219] = 3,
    ACTIONS(288), 1,
      anon_sym_COLON,
    STATE(115), 1,
      sym_function_name_self_index,
    ACTIONS(286), 2,
      anon_sym_LPAREN_RPAREN,
      anon_sym_DOT,
  [2230] = 2,
    ACTIONS(290), 1,
      sym_identifier,
    STATE(110), 2,
      sym__function_name,
      sym_function_name_dot_index,
  [2238] = 2,
    ACTIONS(292), 1,
      sym_identifier,
    STATE(114), 2,
      sym__function_name,
      sym_function_name_dot_index,
  [2246] = 3,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(294), 1,
      anon_sym_EQ,
    STATE(109), 1,
      aux_sym_variable_list_repeat1,
  [2256] = 3,
    ACTIONS(282), 1,
      anon_sym_EQ,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    STATE(109), 1,
      aux_sym_variable_list_repeat1,
  [2266] = 2,
    ACTIONS(299), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(301), 1,
      anon_sym_DOT,
  [2273] = 2,
    ACTIONS(303), 1,
      sym_identifier,
    STATE(88), 1,
      sym_identifier_list,
  [2280] = 2,
    ACTIONS(305), 1,
      sym_identifier,
    STATE(89), 1,
      sym_identifier_list,
  [2287] = 1,
    ACTIONS(307), 2,
      anon_sym_LPAREN_RPAREN,
      anon_sym_DOT,
  [2292] = 2,
    ACTIONS(301), 1,
      anon_sym_DOT,
    ACTIONS(309), 1,
      anon_sym_LPAREN_RPAREN,
  [2299] = 1,
    ACTIONS(311), 2,
      anon_sym_LPAREN_RPAREN,
      anon_sym_DOT,
  [2304] = 1,
    ACTIONS(313), 1,
      sym_identifier,
  [2308] = 1,
    ACTIONS(315), 1,
      sym_identifier,
  [2312] = 1,
    ACTIONS(317), 1,
      anon_sym_EQ,
  [2316] = 1,
    ACTIONS(319), 1,
      sym_identifier,
  [2320] = 1,
    ACTIONS(321), 1,
      sym_identifier,
  [2324] = 1,
    ACTIONS(323), 1,
      anon_sym_EQ,
  [2328] = 1,
    ACTIONS(325), 1,
      ts_builtin_sym_end,
  [2332] = 1,
    ACTIONS(327), 1,
      anon_sym_end,
  [2336] = 1,
    ACTIONS(329), 1,
      anon_sym_end,
  [2340] = 1,
    ACTIONS(331), 1,
      anon_sym_end,
  [2344] = 1,
    ACTIONS(333), 1,
      sym_identifier,
  [2348] = 1,
    ACTIONS(335), 1,
      ts_builtin_sym_end,
  [2352] = 1,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
  [2356] = 1,
    ACTIONS(337), 1,
      sym_identifier,
  [2360] = 1,
    ACTIONS(339), 1,
      anon_sym_end,
  [2364] = 1,
    ACTIONS(341), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 87,
  [SMALL_STATE(6)] = 118,
  [SMALL_STATE(7)] = 145,
  [SMALL_STATE(8)] = 172,
  [SMALL_STATE(9)] = 218,
  [SMALL_STATE(10)] = 262,
  [SMALL_STATE(11)] = 289,
  [SMALL_STATE(12)] = 316,
  [SMALL_STATE(13)] = 345,
  [SMALL_STATE(14)] = 378,
  [SMALL_STATE(15)] = 415,
  [SMALL_STATE(16)] = 454,
  [SMALL_STATE(17)] = 491,
  [SMALL_STATE(18)] = 518,
  [SMALL_STATE(19)] = 547,
  [SMALL_STATE(20)] = 580,
  [SMALL_STATE(21)] = 613,
  [SMALL_STATE(22)] = 646,
  [SMALL_STATE(23)] = 687,
  [SMALL_STATE(24)] = 714,
  [SMALL_STATE(25)] = 755,
  [SMALL_STATE(26)] = 794,
  [SMALL_STATE(27)] = 820,
  [SMALL_STATE(28)] = 842,
  [SMALL_STATE(29)] = 864,
  [SMALL_STATE(30)] = 898,
  [SMALL_STATE(31)] = 932,
  [SMALL_STATE(32)] = 956,
  [SMALL_STATE(33)] = 978,
  [SMALL_STATE(34)] = 1006,
  [SMALL_STATE(35)] = 1036,
  [SMALL_STATE(36)] = 1068,
  [SMALL_STATE(37)] = 1102,
  [SMALL_STATE(38)] = 1136,
  [SMALL_STATE(39)] = 1164,
  [SMALL_STATE(40)] = 1186,
  [SMALL_STATE(41)] = 1220,
  [SMALL_STATE(42)] = 1251,
  [SMALL_STATE(43)] = 1282,
  [SMALL_STATE(44)] = 1311,
  [SMALL_STATE(45)] = 1342,
  [SMALL_STATE(46)] = 1373,
  [SMALL_STATE(47)] = 1392,
  [SMALL_STATE(48)] = 1409,
  [SMALL_STATE(49)] = 1428,
  [SMALL_STATE(50)] = 1445,
  [SMALL_STATE(51)] = 1462,
  [SMALL_STATE(52)] = 1481,
  [SMALL_STATE(53)] = 1498,
  [SMALL_STATE(54)] = 1515,
  [SMALL_STATE(55)] = 1532,
  [SMALL_STATE(56)] = 1551,
  [SMALL_STATE(57)] = 1565,
  [SMALL_STATE(58)] = 1581,
  [SMALL_STATE(59)] = 1597,
  [SMALL_STATE(60)] = 1613,
  [SMALL_STATE(61)] = 1625,
  [SMALL_STATE(62)] = 1641,
  [SMALL_STATE(63)] = 1657,
  [SMALL_STATE(64)] = 1673,
  [SMALL_STATE(65)] = 1689,
  [SMALL_STATE(66)] = 1705,
  [SMALL_STATE(67)] = 1721,
  [SMALL_STATE(68)] = 1737,
  [SMALL_STATE(69)] = 1753,
  [SMALL_STATE(70)] = 1769,
  [SMALL_STATE(71)] = 1785,
  [SMALL_STATE(72)] = 1801,
  [SMALL_STATE(73)] = 1817,
  [SMALL_STATE(74)] = 1833,
  [SMALL_STATE(75)] = 1845,
  [SMALL_STATE(76)] = 1861,
  [SMALL_STATE(77)] = 1877,
  [SMALL_STATE(78)] = 1893,
  [SMALL_STATE(79)] = 1909,
  [SMALL_STATE(80)] = 1925,
  [SMALL_STATE(81)] = 1941,
  [SMALL_STATE(82)] = 1957,
  [SMALL_STATE(83)] = 1973,
  [SMALL_STATE(84)] = 1989,
  [SMALL_STATE(85)] = 2005,
  [SMALL_STATE(86)] = 2021,
  [SMALL_STATE(87)] = 2037,
  [SMALL_STATE(88)] = 2051,
  [SMALL_STATE(89)] = 2062,
  [SMALL_STATE(90)] = 2075,
  [SMALL_STATE(91)] = 2085,
  [SMALL_STATE(92)] = 2093,
  [SMALL_STATE(93)] = 2109,
  [SMALL_STATE(94)] = 2119,
  [SMALL_STATE(95)] = 2129,
  [SMALL_STATE(96)] = 2139,
  [SMALL_STATE(97)] = 2147,
  [SMALL_STATE(98)] = 2155,
  [SMALL_STATE(99)] = 2165,
  [SMALL_STATE(100)] = 2173,
  [SMALL_STATE(101)] = 2181,
  [SMALL_STATE(102)] = 2191,
  [SMALL_STATE(103)] = 2199,
  [SMALL_STATE(104)] = 2210,
  [SMALL_STATE(105)] = 2219,
  [SMALL_STATE(106)] = 2230,
  [SMALL_STATE(107)] = 2238,
  [SMALL_STATE(108)] = 2246,
  [SMALL_STATE(109)] = 2256,
  [SMALL_STATE(110)] = 2266,
  [SMALL_STATE(111)] = 2273,
  [SMALL_STATE(112)] = 2280,
  [SMALL_STATE(113)] = 2287,
  [SMALL_STATE(114)] = 2292,
  [SMALL_STATE(115)] = 2299,
  [SMALL_STATE(116)] = 2304,
  [SMALL_STATE(117)] = 2308,
  [SMALL_STATE(118)] = 2312,
  [SMALL_STATE(119)] = 2316,
  [SMALL_STATE(120)] = 2320,
  [SMALL_STATE(121)] = 2324,
  [SMALL_STATE(122)] = 2328,
  [SMALL_STATE(123)] = 2332,
  [SMALL_STATE(124)] = 2336,
  [SMALL_STATE(125)] = 2340,
  [SMALL_STATE(126)] = 2344,
  [SMALL_STATE(127)] = 2348,
  [SMALL_STATE(128)] = 2352,
  [SMALL_STATE(129)] = 2356,
  [SMALL_STATE(130)] = 2360,
  [SMALL_STATE(131)] = 2364,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chunk, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_sub_index, 4, .production_id = 6),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_sub_index, 4, .production_id = 6),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_dot_index, 3, .production_id = 3),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_dot_index, 3, .production_id = 3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_list, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_list, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_list_repeat1, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_list_repeat1, 2),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chunk_repeat1, 2),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_chunk_repeat1, 2),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chunk_repeat1, 2), SHIFT_REPEAT(112),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chunk_repeat1, 2), SHIFT_REPEAT(107),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chunk_repeat1, 2), SHIFT_REPEAT(92),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chunk_repeat1, 2), SHIFT_REPEAT(111),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chunk_repeat1, 2), SHIFT_REPEAT(106),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chunk, 1),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier_list, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_identifier_list_repeat1, 2),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2), SHIFT_REPEAT(116),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier_list, 1),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2), SHIFT_REPEAT(120),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_list_repeat1, 2), SHIFT_REPEAT(79),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_list_repeat1, 2), SHIFT_REPEAT(65),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_list, 2),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_list, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_local_assign_statement, 2, .production_id = 1),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_assign_statement, 2, .production_id = 1),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_assign_statement, 4, .production_id = 4),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_local_assign_statement, 4, .production_id = 4),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration_statement, 4, .production_id = 5),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 1),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminated_chunk, 1),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_terminated_chunk, 1),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminated_chunk, 2),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_terminated_chunk, 2),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminated_chunk, 3),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_terminated_chunk, 3),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assign_statement, 3, .production_id = 2),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_statement, 3, .production_id = 2),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration_statement, 4, .production_id = 5),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_dot_index, 3, .production_id = 3),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 2),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2), SHIFT_REPEAT(104),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_self_index, 2, .production_id = 7),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_dot_index, 4, .production_id = 3),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [325] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chunk, 2),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lpp(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
